id: I29BAFC95
legacy_id: P000295
ocr_import_info:
  bdrc_scan_id: W30434
  source: bdrc
  ocr_info:
    timestamp: '2020-03-10T08:29:59'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T11:21:28.362977+00:00'
last_modified: 2022-08-27 19:21:59.667387
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W30434
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW30434
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དགེ་བའི་བཤེས་གཉེན་ཆེན་པོ་ཤེས་རབ་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.9455306385510975
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG14929:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG14929
      total_pages: 544
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG14929.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9455306385510975
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
